// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1cXfJYphnTaI9G4dw_dzDIFHdIsSA5eo',
    appId: '1:347681121059:web:a03f32fd0eff88d7732296',
    messagingSenderId: '347681121059',
    projectId: 'expensetracker-4ccfe',
    authDomain: 'expensetracker-4ccfe.firebaseapp.com',
    storageBucket: 'expensetracker-4ccfe.appspot.com',
    measurementId: 'G-X76L2WCHPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULhJ38-x-dXUgwpYmxPCr28hpHjJXxcE',
    appId: '1:347681121059:android:1a9e3392644e95f3732296',
    messagingSenderId: '347681121059',
    projectId: 'expensetracker-4ccfe',
    storageBucket: 'expensetracker-4ccfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuI05slsqlw3E8nx94cgVvPInWpMfH0sk',
    appId: '1:347681121059:ios:3d0334034cc75476732296',
    messagingSenderId: '347681121059',
    projectId: 'expensetracker-4ccfe',
    storageBucket: 'expensetracker-4ccfe.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuI05slsqlw3E8nx94cgVvPInWpMfH0sk',
    appId: '1:347681121059:ios:3d0334034cc75476732296',
    messagingSenderId: '347681121059',
    projectId: 'expensetracker-4ccfe',
    storageBucket: 'expensetracker-4ccfe.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1cXfJYphnTaI9G4dw_dzDIFHdIsSA5eo',
    appId: '1:347681121059:web:7d9be960c1bb1af3732296',
    messagingSenderId: '347681121059',
    projectId: 'expensetracker-4ccfe',
    authDomain: 'expensetracker-4ccfe.firebaseapp.com',
    storageBucket: 'expensetracker-4ccfe.appspot.com',
    measurementId: 'G-VHREW2R9D3',
  );
}
